ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retorna_municipio/', views.retorna_municipio, name="retorna-municipio"),
    path('retorna_tremestre/', views.retorna_tremestre, name="retorna-tremestre"),
    path('retorna_as_unidadeCurricular/', views.retorna_as_unidadeCurricular, name="retorna-unidadeCurricular"),
]

arquivo/urls.py
from django.urls import path
from . import views

app_name = 'arquivo'

urlpatterns = [
  path('registar_arquivos/', views.registar_arquivos, name='registar-arquivos'),
  path('atualizar_arquivos/<int:pk>/', views.atualizar_arquivos, name='atualizar-arquivos'),
  path('listar_arquivos/', views.listar_arquivos, name='listar-arquivos'),
  path('atualizar_arquivos/<int:pk>/', views.atualizar_arquivos, name='atualizar-arquivos'),
  path('eliminar_arquivos/<int:pk>/', views.eliminar_arquivos, name='eliminar-arquivos'),
  path('visualizar_arquivo/<int:pk>/', views.visualizar_arquivo, name='visualizar-arquivo'),
]

kanguita/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('aluno/', include('aluno.urls')),
    path('ajax/', include('ajax.urls')),
    path('unidade_curricular/', include('unidade_curricular.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('curso/', include('curso.urls')),
    path('docente/', include('docente.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

arquivo/models.py
from django.db import models
#from django.contrib import admin



class Tipologia(models.Model):
    nome = models.CharField(max_length=150)
    def __str__ (self):
        return "%s" % (self.nome)


class Categoria_Partilha(models.Model):
    nome = models.CharField(max_length=150)
    def __str__ (self):
        return "%s" % (self.nome)


# Create your models here.
class Arquivo(models.Model):
    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=170, blank=True, null=True)
    numero_pagina = models.CharField(max_length=5, null=True, blank=True, default="")
    tipologia = models.ForeignKey(Tipologia, on_delete=models.CASCADE, parent_link=True)
    partilha = models.ForeignKey(Categoria_Partilha, on_delete=models.SET_NULL, parent_link=True,  blank=True, null=True, default="")
    data = models.DateField()
    arquivo = models.FileField(upload_to="uploads/%Y/")
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

   
    class Meta:
        ordering = ['titulo']
    def __str__ (self):
        return self.id

arquivo/forms.py
from django import forms
from django.forms import ModelForm
from arquivo.models import Arquivo


class Arquivo_Form(ModelForm):
    class Meta:
        arquivo = forms.FileField()
        model = Arquivo
        fields = ['titulo', 'autor', 'numero_pagina', 'tipologia', 'data', 'partilha', 'arquivo']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'autor': forms.TextInput(attrs={'class': 'form-control'}),
            'numero_pagina': forms.TextInput(attrs={'class': 'form-control'}),
            'data': forms.TextInput(attrs={'type':'date', 'class': 'form-control'}),
            'tipologia': forms.Select(attrs={'class': 'form-control'}),
            'partilha': forms.Select(attrs={'class': 'form-control'}),
        }


class ConsultarForm(forms.Form):
    nome = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

arquivo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, FileResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.db.models import Q
from django.urls import reverse
import  sweetify, os
from django.conf import settings
from arquivo.models import Arquivo, Tipologia
from arquivo.forms import Arquivo_Form, ConsultarForm


#@login_required
def visualizar_arquivo(request, pk):
    resp = Arquivo.objects.get(id=pk)
    filepath = os.path.join(settings.MEDIA_ROOT)
    nome = resp.arquivo
    files = filepath +"/"+str(nome)
    print(files)
    """with open(filepath +"/"+str(nome), 'r') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename='+nome+'.pdf'
        return response"""
    
    context = {'lista': resp, 'nome':filepath +"/"+str(nome)}
    return render (request, 'arquivos/visualizar_arquivo.html', context)


#@login_required
def listar_arquivos(request):
    lista = Arquivo.objects.select_related().all().order_by('-titulo')
    context = {'lista':lista}
    return render (request, 'arquivos/listar_arquivos.html', context)


#@login_required
def eliminar_arquivos(request, pk):
    if pk > 0:
        lista = Arquivo.objects.get(id=pk).delete()
        sweetify.success(request,'Dados eliminado comsucesso!....', timer='4900', button='Ok')
        #return HttpResponseRedirect(reverse('secretaria:listar-modulos-mestrado'))
        return HttpResponseRedirect(reverse('arquivo:listar-arquivos'))


#@login_required
def procura_arquivos(request):
    form = ConsultarForm(request.POST or None)
    if request.method == "POST":
        nome = request.POST['nome'].upper()
        lista = Arquivo.objects.filter(Q(titulo__contains=nome) | Q(autor__contains=nome))
        context = {'lista': lista}
        return render (request, 'arquivos/listar_arquivos.html', context)

    context = {'form': form}
    return render (request, 'arquivos/procura_arquivos.html', context)


#@login_required
#FUNÇÃO QUE VAI ATUALIZAR OS DADOS DE UM ARQUIVO
def atualizar_arquivos(request, pk):
    resp = Arquivo.objects.get(id=pk)
    form = Arquivo_Form(request.POST or None, instance=resp)
    if request.method == "POST":
        form = Arquivo_Form(request.POST, request.FILES, instance=resp)
        if form.is_valid():
            form.save()
            sweetify.success(request,'Arquivo Atualizado com sucesso!....', timer='4900', button='Ok')
            return HttpResponseRedirect(reverse('arquivo:listar-arquivos'))
    
    context = {'form': form, 'pk': resp.id }
    return render (request, 'arquivos/adicionar_arquivo.html', context)


#@login_required
def registar_arquivos(request):
    form = Arquivo_Form(request.POST or None)
    if request.method == "POST":
        form = Arquivo_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            sweetify.success(request,'Arquivo Registado com sucesso!....', timer='4900', button='Ok')
            form = Arquivo_Form()
        
    #print(form.errors)
    context = {'form': form}
    return render (request, 'arquivos/adicionar_arquivo.html', context)

templates/arquivos/adicionar_arquivo.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
    <div class="card" style="min-height: 484px">
      {% if pk is not null %}
      <div class="card-header">
        <h3>Editar Dados do Arquivo</h3>
      </div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'arquivo:atualizar-arquivos' pk %}" method="POST" enctype="multipart/form-data">
          {% else %}
          <div class="card-header">
            <h3>Adicionar Novo Arquivo</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'arquivo:registar-arquivos' %}" method="POST" enctype="multipart/form-data">
              {% endif %} {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Titulo<span class="text-danger">*</span></label>
                    {{ form.titulo }}{{ form.titulo.errors }}
                    
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Autor</label>
                    {{ form.autor }}{{ form.autor.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Número de Pagina<span class="text-danger">*</span></label>
                    {{ form.numero_pagina }}{{ form.numero_pagina.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Categoria<span class="text-danger">*</span></label>
                    {{ form.tipologia }}{{ form.tipologia.errors }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Data de Criação</label>
                    {{ form.data }}{{ form.data.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Tipo de Partilha</label>
                    {{ form.partilha }}{{ form.partilha.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Arquivo</label>
                    {{ form.arquivo }}{{ form.arquivo.errors }}
                  
                  </div>
                </div>

              </div>

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">SALVAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/arquivos/listar_arquivos.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 12:33:14
@modify date 2021-12-28 17:10:14
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista de Arquivos Disponivel</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Autor</th>
          <th>Titulo</th>
          <th>Tipologia</th>
          <th>Nº de Pagins</th>
          <th>Opção Partilha</th>
          <th>Data</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">{{ dados.autor|upper }}</td>
          <td class="">{{ dados.titulo|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.tipologia|upper }}</td>
          <td class="">{{ dados.numero_pagina }}</td>
          <td class="">{{ dados.partilha }}</td>
          <td class="">{{ dados.data|upper }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'arquivo:visualizar-arquivo' dados.id %}">VISUALIZAR</a>
                  <a class="dropdown-item" href="{% url 'arquivo:atualizar-arquivos' dados.id %}">ATUALIZAR</a>
                  <a class="dropdown-item" href="{% url 'arquivo:eliminar-arquivos' dados.id %}">ELIMINAR</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/arquivos/visualizar_arquivo.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Visualização do Arquivo - {{ lista.arquivo }}</h3></div>
  <div class="card-body">
    <div class="x_content">
      <object type="application/pdf" data="{{ nome }}" width="250" height="200"></object>
    </div>
  </div>
</div>
{% endblock %}