ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retorna_municipio/', views.retorna_municipio, name="retorna-municipio"),
    path('retorna_tremestre/', views.retorna_tremestre, name="retorna-tremestre"),
    path('retorna_as_unidadeCurricular/', views.retorna_as_unidadeCurricular, name="retorna-unidadeCurricular"),
]

arquivo/urls.py
from django.urls import path
from . import views

app_name = 'arquivo'

urlpatterns = [
  path('registar_arquivos/', views.registar_arquivos, name='registar-arquivos'),
  path('atualizar_arquivos/<int:pk>/', views.atualizar_arquivos, name='atualizar-arquivos'),
  path('listar_arquivos/', views.listar_arquivos, name='listar-arquivos'),
  path('atualizar_arquivos/<int:pk>/', views.atualizar_arquivos, name='atualizar-arquivos'),
  path('eliminar_arquivos/<int:pk>/', views.eliminar_arquivos, name='eliminar-arquivos'),
  path('visualizar_arquivo/<int:pk>/', views.visualizar_arquivo, name='visualizar-arquivo'),
]

biblioteca/urls.py
from django.urls import path
from . import views

app_name = 'biblioteca'
urlpatterns = [

  path('adicionarNova_obraLiteraria/', views.adicionarNova_obraLiteraria, name='adicionarNova-obraLiteraria'),
  path('listar_obras/', views.listar_obras, name='listar-obras'),
  path('atualizar_obra_literaria/<int:pk>/', views.atualizar_obra_literaria, name='atualizar-obra-literaria'),
  path('consultar_obra/', views.consultaObra, name='consulta-obra'),
  path('solicitacaoEmpresto_obraLiterarias/', views.solicitacaoEmpresto_obraLiteraria, name='solicitacaoEmpresto-obraLiteraria'),

]

kanguita/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('aluno/', include('aluno.urls')),
    path('ajax/', include('ajax.urls')),
    path('unidade_curricular/', include('unidade_curricular.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('curso/', include('curso.urls')),
    path('docente/', include('docente.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

biblioteca/models.py
from django.db import models

# Create your models here. 
class Categoria_livro(models.Model):
    nome = models.CharField(max_length=100,null=True, blank=True, default="")
   
    def __str__ (self):
        return "%s" % (self.nome)


class Livro(models.Model):
    categoria = models.ForeignKey(Categoria_livro, on_delete=models.SET_NULL, blank=True, null=True, parent_link=True)
    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    numero_pagina = models.CharField(max_length=5, null=True, blank=True, default="")
    isbn = models.CharField(max_length=14, null=True, blank=True, default="")
    data_entrada = models.CharField(max_length=100)
    data_publicacao = models.DateField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    arquivo = models.FileField(upload_to="livro/%Y/")

    class Meta:
        ordering = ['titulo']
    def __str__ (self):
        return self.id
        
        

biblioteca/forms.py
from django import forms
from django.forms import ModelForm
from biblioteca.models import Livro



class Livro_Form(ModelForm):
    class Meta:
        arquivo = forms.FileField()
        model = Livro
        fields = ['categoria','titulo', 'autor', 'numero_pagina', 'isbn', 'data_entrada', 'data_publicacao', 'arquivo']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'autor': forms.TextInput(attrs={'class': 'form-control'}),
            'numero_pagina': forms.TextInput(attrs={'class': 'form-control'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control'}),
            'data_entrada': forms.TextInput(attrs={'type':'date', 'class': 'form-control'}),
            'data_publicacao': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
        }

"""
class Solicitacao_Obra_Form(ModelForm):
    aluno = forms.CharField(max_length=14, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Solicitacao
        fields = ['titulo', 'autor', 'data_entrada', 'categoria', 'quantidade']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'autor': forms.TextInput(attrs={'class': 'form-control'}),
            'data_entrada': forms.TextInput(attrs={'type':'date', 'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'quantidade': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_aluno(self):
        aluno = self.cleaned_data.get('aluno')
        id = retorna_id_simples(aluno)
        if id is not None and int(id) > 0:
            return id
        raise forms.ValidationError(" O número do BI não é valido, não existe")
"""

class ConsultarForm(forms.Form):
    nome = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    #nome = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

biblioteca/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, FileResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.db.models import Q
from django.urls import reverse
import  sweetify, os
from django.conf import settings
from biblioteca.models import Livro
from biblioteca.forms import Livro_Form,ConsultarForm


# Create your views here.

#@login_required
def listar_obras(request):
    lista = Livro.objects.select_related('categoria').all().order_by('-titulo')
    context = {'lista':lista}
    return render (request, 'biblioteca/listar_livros.html', context)



#@login_required
# função que vai efetuar a consulta dos dads quando for solicitado pela routa
def consultaObra(request):
    form = ConsultarForm(request.POST or None)
    if request.method == "POST":
        nome = request.POST['nome']
        lista = Livro.objects.filter(Q(titulo__contains=nome) | Q(autor__contains=nome))
        context = {'lista': lista}
        return render (request, 'biblioteca/listar_livros.html', context)

    context = {'form': form}
    return render (request, 'biblioteca/consultar_obras.html', context)



#@login_required
def solicitacaoEmpresto_obraLiteraria(request):
    form = "" #Solicitacao_Obra_Form(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            aluno = form.cleaned_data.get('aluno')
            fro = form.save(commit=False)
            fro.aluno_id = aluno
            fro.save()
            sweetify.success(request,'Solicitação efectuada com sucesso!....', timer='4900', button='Ok', footer=SOFIL_WEB)
            return HttpResponseRedirect(reverse('secretaria:home'))
    #print(form.errors)
    context = {'form': form}
    return render (request, 'biblioteca/registar_solicitacao_obra.html', context)


#@login_required
def atualizar_obra_literaria(request, pk):
    resp = Livro.objects.get(id=pk)
    form = Livro_Form(request.POST or None, instance=resp)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            sweetify.success(request,'Dados atualizado com sucesso!....', timer='4900', button='Ok')
            return HttpResponseRedirect(reverse('biblioteca:listar-obras'))
    #print(form.errors)
    context = {'form': form, 'pk': resp.id}
    return render (request, 'biblioteca/adicionarNova_obraLiteraria.html', context)


#@login_required
def adicionarNova_obraLiteraria(request):
    form = Livro_Form(request.POST or None)
    if request.method == "POST":
        form = Livro_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            sweetify.success(request,'Inserido com sucesso!..', timer='4900', button='Ok')
            #return HttpResponseRedirect(reverse('secretaria:home'))
            form = Livro_Form()
    
    context = {'form': form}
    return render (request, 'biblioteca/adicionarNova_obraLiteraria.html', context)

templates/biblioteca/adicionarNova_obraLiteraria.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
    <div class="card" style="min-height: 484px">

       {% if pk is not null %}
      <div class="card-header">
        <h3>Editar Dados da Obra Literaria</h3>
      </div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'biblioteca:atualizar-obra-literaria' pk %}" method="POST" enctype="multipart/form-data">
       {% else %}
          <div class="card-header">
        <h3>Adicionar Nova Obra Literaria</h3>
      </div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'biblioteca:adicionarNova-obraLiteraria' %}" method="POST" enctype="multipart/form-data">
        
               {% endif %}{% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Titulo</label>
                    {{ form.titulo }}{{ form.titulo.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Autor</label>
                    {{ form.autor }}{{ form.autor.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Número de Pagina</label>
                    {{ form.numero_pagina }}{{ form.numero_pagina.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Categoria</label>
                    {{ form.categoria }}{{ form.categoria.errors }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Isban:</label>
                    {{ form.isbn }}{{ form.isbn.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Data de publicação</label>
                    {{ form.data_publicacao }}{{ form.data_publicacao.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Data de Entrada</label>
                    {{ form.data_entrada }}{{ form.data_entrada.errors }}
                  </div>
                </div>
                
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Arquivo</label>
                    {{ form.arquivo }}{{ form.arquivo.errors }}

                  </div>
                </div>

              </div>

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">SALVAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/biblioteca/consultar_obras.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
    <div class="card" style="min-height: 484px">

     
          <div class="card-header">
        <h3>Consultar Obra Literária</h3>
      </div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'biblioteca:consulta-obra' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Titulo / Nome do Autor</label>
                    {{ form.nome }}{{ form.nome.errors }}
                  </div>
                </div>
               
              </div>

             
              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">CONSULTAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/biblioteca/listar_livros.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-01-03 16:46:31
@modify date 2022-01-03 18:08:50
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista de Livros Disponivel</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Titulo</th>
          <th>Autor</th>
          <th>Categoria</th>
          <th>Isban</th>
          <th>Data de Publicação</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">{{ dados.titulo|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.autor|upper }}</td>
          <td class="">{{ dados.categoria|upper }}</td>
          <td class="">{{ dados.isbn }}</td>
          <td class="">{{ dados.data_publicacao|upper }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'arquivo:visualizar-arquivo' dados.id %}">SOLICITAR EMPRESTADO</a>
                  <a class="dropdown-item" href="{% url 'biblioteca:atualizar-obra-literaria' dados.id %}">ATUALIZAR</a>
                  <a class="dropdown-item" href="{% url 'arquivo:eliminar-arquivos' dados.id %}">DESATIVAR</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}