ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retorna_municipio/', views.retorna_municipio, name="retorna-municipio"),
    path('retorna_tremestre/', views.retorna_tremestre, name="retorna-tremestre"),
    path('retorna_as_unidadeCurricular/', views.retorna_as_unidadeCurricular, name="retorna-unidadeCurricular"),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'

urlpatterns = [
  path('adicionarNovo_cursos/', views.adicionarNovo_cursos, name='adicionarNovo-cursos'),
  path('listar_cursos/', views.listar_cursos, name='listar-cursos'),
  path('atualizar_dadosCurso/<int:pk>/', views.atualizar_dadosCurso, name='atualizar-dadosCurso'),

 
]

kanguita/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('aluno/', include('aluno.urls')),
    path('ajax/', include('ajax.urls')),
    path('unidade_curricular/', include('unidade_curricular.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('curso/', include('curso.urls')),
    path('docente/', include('docente.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

unidade_curricular/urls.py
  
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'unidade_curricular'
urlpatterns = [
    path('adicionarNova_unidadeCurricular/', views.adicionarUnidadeCurricular, name= "nova-unidadeCurricular"),
    path('listarunidadeCurricular/', views.listarUnidadeCurricular, name= "listar-unidadeCurricular"),
    path('editarUnidadeCurricular/<int:pk>/', views.editarUnidadeCurricular, name= "editar-UnidadeCurricular"),
    path('definir_unidadeCurricular_curso/', views.definir_unidadeCurricular_curso, name= "definir-unidadeCurricular-curso"),
    path('listarUnidadeCurricular_cada_curso/', views.listarUnidadeCurricular_cada_curso, name= "listarUnidadeCurricular-cada-curso"),
]

unidade_curricular/models.py
"""
 * @author [Gunza Ismael]
 * @email [7ilip@gmail.com]
 * @create date 2021-12-27 09:25:48
 * @modify date 2021-12-27 09:25:48
 * @desc [description]
 */
"""

from django.db import models
from curso.models import Curso
from config.models import Ano, Tremestre
# Create your models here.


class UnidadeCurricular(models.Model):
    nome = models.CharField(max_length=100)
    sigla = models.CharField(max_length=60, blank=True, null=True, default=" ")
    codigo = models.CharField(max_length=20, blank=True, null=True, default="")
    carga_horaria = models.CharField(max_length=20, blank=True, null=True, default="")
    data_create= models.DateField(auto_now=True)

    def __str__(self):
        return "%s" % (self.nome)



class UnidadeCurricular_Curso(models.Model):
    ano = models.ForeignKey(Ano, on_delete=models.CASCADE, parent_link=True)
    tremestre = models.ForeignKey(Tremestre, on_delete=models.CASCADE, parent_link=True)
    unidade_curricular = models.ForeignKey(UnidadeCurricular, on_delete=models.CASCADE, parent_link=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, parent_link=True)
    ano_academico = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    carga_horaria = models.CharField(max_length=20, blank=True, null=True, default="")

    def __str__ (self):
        return "%s" % (self.unidade_curricular.nome)

unidade_curricular/forms.py
from django import forms
from django.forms import ModelForm
from unidade_curricular.models import UnidadeCurricular, UnidadeCurricular_Curso



class UnidadeCurricularForm(ModelForm):
    class Meta:
        model = UnidadeCurricular
        fields = ['nome', 'codigo', 'sigla', 'carga_horaria']
        widgets = {
            'sigla': forms.TextInput(attrs={'class': 'form-control'}),
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'codigo': forms.TextInput(attrs={'class': 'form-control'}),
            'carga_horaria': forms.TextInput(attrs={'class': 'form-control'}),
            
        }
        

class UnidadeCurricular_Curso_Form(ModelForm):
    class Meta:
        model =  UnidadeCurricular_Curso
        fields = ('curso', 'unidade_curricular', 'ano', 'tremestre', 'ano_academico')
        widgets = {
            'ano_academico': forms.TextInput(attrs={'class': 'form-control'}),
            'unidade_curricular': forms.Select(attrs={'class': 'form-control'}),
            'curso': forms.Select(attrs={'class': 'form-control'}),
            'ano': forms.Select(attrs={'class': 'form-control'}),
            'tremestre': forms.Select(attrs={'class': 'form-control'}),
        }


class listarUnidadeCurricular_cada_curso_Form(ModelForm):
    class Meta:
        model = UnidadeCurricular_Curso
        fields = ('curso',)
        widgets = {
            'curso': forms.Select(attrs={'class': 'form-control'}),
        }

unidade_curricular/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import sweetify
from unidade_curricular.models import UnidadeCurricular, UnidadeCurricular_Curso
from unidade_curricular.forms import (UnidadeCurricularForm, UnidadeCurricular_Curso_Form, listarUnidadeCurricular_cada_curso_Form)
# Create your views here.



def listarUnidadeCurricular(request):
    lista =[]
    lista = UnidadeCurricular.objects.all()
    context = {'lista': lista}
    return render (request, 'unidadeCurricular/listarUnidadeCurricular.html', context)



#@login_required
def listarUnidadeCurricular_cada_curso(request):
    form = listarUnidadeCurricular_cada_curso_Form(request.POST or None)
    if request.method == "POST":
        curso = request.POST.get('curso')
        lista = UnidadeCurricular_Curso.objects.select_related('curso').filter(curso_id=curso).order_by('-id')
        context = {'lista':lista}
        return render (request, 'unidadeCurricular/lista_unidadeCada_curso.html', context)
    context = {'form':form}
    return render (request, 'unidadeCurricular/forms_listar_unidadeCurso.html', context)


# Editar dados da unidade curricular 
def editarUnidadeCurricular(request, pk):
    resp = UnidadeCurricular.objects.get(pk=pk)
    form = UnidadeCurricularForm(request.POST or None, instance=resp)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            sweetify.success(request,'Dados atualizado com sucesso',button='Ok', timer='3100', persistent="Close")
            return HttpResponseRedirect(reverse('unidade_curricular:listar-unidadeCurricular'))
    
    context = {'form':form, 'pk':pk}
    return render (request, 'unidadeCurricular/adicionarUnidadeCurricular.html', context)



def  definir_unidadeCurricular_curso(request):
    form =  UnidadeCurricular_Curso_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            sweetify.success(request, 'Inserida com sucesso!....', button='Ok', timer='3100', persistent="Close")
            form = UnidadeCurricular_Curso_Form()
           
    context = {'form':form}
    return render (request, 'unidadeCurricular/definir_unidadeCurricular_curso.html', context)



def adicionarUnidadeCurricular(request):
    form = UnidadeCurricularForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            sweetify.success(request, 'Unidade Curricular registrada com sucesso!....', button='Ok', timer='3100', persistent="Close")

            form = UnidadeCurricularForm()
            #return render (request, 'unidadeCurricular/adicionarUnidadeCurricular.html', context)

    context = {'form':form}
    return render (request, 'unidadeCurricular/adicionarUnidadeCurricular.html', context)

templates/unidadeCurricular/adicionarUnidadeCurricular.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card" style="min-height: 484px">
      {% if pk is not null %}
      <div class="card-header"><h3>Editar Dados da Unidade Curricular</h3></div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'unidade_curricular:editar-UnidadeCurricular' pk %}" method="POST">
        {% else %}
        <div class="card-header"><h3>Adicionar Nova Unidade Curricular</h3></div>
        <div class="card-body">
          <form class="forms-sample" action="{% url 'unidade_curricular:nova-unidadeCurricular' %}" method="POST">
            {% endif %} {% csrf_token %} {% autoescape on %}
            <div class="form-group row">
              <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Nome</label>
              <div class="col-sm-9">{{ form.nome }}{{ form.nome.errors }}</div>
            </div>
            <div class="form-group row">
              <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Sigla</label>
              <div class="col-sm-9">{{ form.sigla }}{{ form.sigla.errors }}</div>
            </div>
            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Carga Horaria</label>
              <div class="col-sm-9">{{ form.carga_horaria }}{{ form.carga_horaria.errors }}</div>
            </div>
            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Codigo</label>
              <div class="col-sm-9">{{ form.codigo }}{{ form.codigo.errors }}</div>
            </div>

            <div class="form-group">
              <div id="visitfromworld" style="width: 100%; height: 50px"></div>
            </div>
            <button type="submit" class="btn btn-primary mr-2" style="width: 100%">Salvar</button>
            {% endautoescape %}
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/unidadeCurricular/definir_unidadeCurricular_curso.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card" style="min-height: 484px">
      {% if pk is not null %}
      <div class="card-header">
        <h3>Editar Dados do Curso</h3>
      </div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'curso:atualizar-dadosCurso' pk %}" method="POST" enctype="multipart/form-data">
          {% else %}
          <div class="card-header">
            <h3>Definir as unidade curricular do curso</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'unidade_curricular:definir-unidadeCurricular-curso' %}" method="POST" enctype="multipart/form-data">
              {% endif %} {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Curso<span class="text-danger">*</span></label>
                    {{ form.curso }}{{ form.curso.errors }}
                  </div>
                </div>
                
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Unidade Curricular<span class="text-danger">*</span></label>
                    {{ form.unidade_curricular }}{{ form.unidade_curricular.errors }}
                  </div>
                </div>
                
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Ano<span class="text-danger">*</span></label>
                    {{ form.ano }}{{ form.ano.errors }}
                  </div>
                </div>
                
              </div>
               <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Tremestre<span class="text-danger">*</span></label>
                    {{ form.tremestre }}{{ form.tremestre.errors }}
                  </div>
                </div>
                
              </div>
               
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Ano Academico<span class="text-danger">*</span></label>
                    {{ form.ano_academico }}{{ form.ano_academico.errors }}
                  </div>
                </div>
                
              </div>
             

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">ADICIONAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/unidadeCurricular/forms_listar_unidadeCurso.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card" style="min-height: 484px">
      
          <div class="card-header">
            <h3>Listar unidade curricular de um curso</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'unidade_curricular:listarUnidadeCurricular-cada-curso' %}" method="POST" enctype="multipart/form-data">
             {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Escolha o Curso<span class="text-danger">*</span></label>
                    {{ form.curso }}{{ form.curso.errors }}
                  </div>
                </div>
                
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Unidade Curricular<span class="text-danger">*</span></label>
                    {{ form.unidade_curricular }}{{ form.unidade_curricular.errors }}
                  </div>
                </div>
                
              </div>
               

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">LISTAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/unidadeCurricular/lista_unidadeCada_curso.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 12:33:14
@modify date 2022-01-05 15:03:04
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista das Unidade Curricular</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Curso</th>
          <th>Unidade Curricular</th>
          <th>Ano</th>
          <th>Tremestre</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in lista %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.curso }}</td>
          <td>{{ item.unidade_curricular }}</td>
          <td>{{ item.ano }}h</td>
          <td>{{ item.tremestre }}</td>

          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/unidadeCurricular/listarUnidadeCurricular.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 12:33:14
@modify date 2021-12-27 11:41:44
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista das Unidade Curricular</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>Sigla</th>
          <th>Carga Horária</th>
          <th>Codigo</th>
          <th>Opção</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in lista %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.nome }}</td>
          <td>{{ item.sigla }}</td>
          <td>{{ item.carga_horaria }}h</td>
          <td>{{ item.codigo }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'unidade_curricular:editar-UnidadeCurricular' item.id %}">Editar</a>
                  <a class="dropdown-item" href="#">Desativar</a>
                  <a class="dropdown-item" href="#">Ativar</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}