ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'
urlpatterns = [
    path('retorna_municipio/', views.retorna_municipio, name="retorna-municipio"),
    path('retorna_tremestre/', views.retorna_tremestre, name="retorna-tremestre"),
    path('retorna_as_unidadeCurricular/', views.retorna_as_unidadeCurricular, name="retorna-unidadeCurricular"),
]

docente/urls.py
from django.urls import path
from . import views

app_name = 'docente'

urlpatterns = [
  path('adicionar_docente/', views.adicionar_docente, name='adicionar-docente'),
  path('listar_docente/', views.listar_docente, name='listar-docente'),
  path('atualizar_dados_docente/<int:pk>/', views.atualizar_dados_docente, name='atualizar-dados-docente'),
  path('definirOrientador_teseTcc', views.definirOrientador_teseTcc, name='definirOrientador-tese'),
  path('listar_Orientador_teseTcc/', views.listar_Orientador_teseTcc, name='listar-Orientador-teseTcc'),
  path('atualizar_definirOrientador_teseTcc/<int:pk>/', views.atualizar_definirOrientador_teseTcc, name='atualizar-definirOrientador-teseTcc'),
  path('fecharCandidatura_Orientador_teseTcc/<int:pk>/', views.fecharCandidatura_Orientador_teseTcc, name='fecharCandidatura-Orientador-teseTcc'), 
  path('abriCandidatura_Orientador_teseTcc/<int:pk>/', views.abriCandidatura_Orientador_teseTcc, name='abriCandidatura-Orientador-teseTcc'),
]

kanguita/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('utilizador.urls')),
    path('home/', include('home.urls')),
    path('aluno/', include('aluno.urls')),
    path('ajax/', include('ajax.urls')),
    path('unidade_curricular/', include('unidade_curricular.urls')),
    path('arquivo/', include('arquivo.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('curso/', include('curso.urls')),
    path('docente/', include('docente.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

docente/models.py
from django.db import models
from django.utils import timezone
from pessoa.models import Pessoa
from config.models import Periodo
from unidade_curricular.models import UnidadeCurricular
from curso.models import Curso

# Create your models here.

class Docente_Grau_academico(models.Model):
    nome = models.CharField(max_length=50)
    opcao = models.CharField(max_length=160, blank=True, null=True)
    def __str__ (self):
        return "%s" % (self.nome)


class Categoria(models.Model):
    nome = models.CharField(max_length=50)
    opcao = models.CharField(max_length=160, blank=True, null=True)
    def __str__ (self):
        return "%s" % (self.nome)


class Estado_Docente(models.Model):
    nome = models.CharField(max_length=50)
    opcao = models.CharField(max_length=160, blank=True, null=True)
    def __str__ (self):
        return "%s" % (self.nome)


class Estado_Orientador(models.Model):
    nome = models.CharField(max_length=50)
    opcao = models.CharField(max_length=160, blank=True, null=True)
    def __str__ (self):
        return "%s" % (self.nome)

class Docente(models.Model):
    pessoa= models.ForeignKey(Pessoa, on_delete=models.CASCADE, parent_link=True)
    numero_docente= models.CharField(max_length=10, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, parent_link=True)
    grau_academico = models.ForeignKey(Docente_Grau_academico, on_delete=models.CASCADE, parent_link=True)
    estado= models.ForeignKey(Estado_Docente, on_delete=models.CASCADE, parent_link=True)
    data_registro = models.DateField(default=timezone.now)
    created = models.DateField(blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return 'Dr %s'  % (self.pessoa.nome)


class Orientador(models.Model):
    docente = models.ForeignKey(Docente, on_delete=models.CASCADE, parent_link=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, parent_link=True)
    data_limite = models.DateField(default=timezone.now)
    estado = models.ForeignKey(Estado_Orientador, on_delete=models.CASCADE, parent_link=True)
    numero_orientados = models.IntegerField(default=1)
    created = models.DateField(blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return self.id


"""class Unidade_Curricular_Docente(models.Model):
    docente= models.ForeignKey(Docente, on_delete=models.CASCADE, parent_link=True)
    curso= models.ForeignKey(Docente, on_delete=models.CASCADE, parent_link=True)
    unidadeCurricular = models.ForeignKey(UnidadeCurricular, on_delete=models.CASCADE, parent_link=True)
    periodo = models.ForeignKey(Estado_Docente, on_delete=models.CASCADE, parent_link=True)
    estado = models.ForeignKey(Estado_Docente, on_delete=models.CASCADE, parent_link=True)
    ano = models.ForeignKey(Estado_Docente, on_delete=models.CASCADE, parent_link=True)
    data_registro = models.DateField(default=timezone.now)
    created = models.DateField(blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return '%d'  % (self.id)"""

docente/forms.py
from django import forms
from django.forms import ModelForm
from docente.models import Docente, Orientador
from config.views import gerarNumeroEstudante



class Docente_Form(ModelForm):
    pessoa = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Docente
        fields = ['numero_docente', 'categoria','grau_academico', 'data_registro', 'estado']
        widgets = {
            'numero_docente': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select( attrs={'class': 'form-control '}),
            'estado': forms.Select( attrs={'class': 'form-control '}),
            'grau_academico': forms.Select( attrs={'class': 'form-control '}),
            'data_registro': forms.DateInput(attrs={'type': 'date','class': 'form-control'}),
        }


class OrientadorFrom(ModelForm):
    class Meta:
        model = Orientador
        fields = ['docente','curso', 'data_limite', 'estado','numero_orientados']
        widgets = {
            'docente': forms.Select( attrs={'class': 'form-control '}),
            'estado': forms.Select( attrs={'class': 'form-control '}),
            'curso': forms.Select( attrs={'class': 'form-control '}),
            'data_limite': forms.DateInput(attrs={'type': 'date','class': 'form-control'}),
            'numero_orientados': forms.NumberInput(attrs={'type': 'integer','class': 'form-control'}),
        }


class ConsultarForm(forms.Form):
    nome = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

docente/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import sweetify
from django.db.models import Q
from docente.models import Docente, Orientador
from pessoa.models import Pessoa
from pessoa.forms import Pessoa_Form
from docente.forms import Docente_Form, ConsultarForm, OrientadorFrom
from config.views import prepara_foto

# Create your views here.


#@login_required
def listar_docente(request):
    lista = Docente.objects.select_related('pessoa').all().order_by('-pessoa')
    context = {'lista': lista}
    return render (request, 'docente/listar_docente.html', context)


def listar_Orientador_teseTcc(request):
    lista = Orientador.objects.select_related('docente').all().order_by('-docente')
    context = {'lista': lista}
    return render (request, 'docente/listar_Orientador.html', context)


def abriCandidatura_Orientador_teseTcc(request, pk):
    if pk > 0:
        orientador = Orientador.objects.get(id=pk)
        orientador.estado_id = 1
        orientador.save()
        sweetify.success(request,'Candidatura aberta com sucesso', button='Ok', timer='3100', persistent="Close")
        return HttpResponseRedirect(reverse('docente:listar-Orientador-teseTcc'))

    sweetify.error(request,'solicitação invalida', button='Ok', timer='3100', persistent="Close")
    return HttpResponseRedirect(reverse('docente:listar-Orientador-teseTcc'))


def fecharCandidatura_Orientador_teseTcc(request, pk):
    if pk > 0:
        orientador = Orientador.objects.get(id=pk)
        orientador.estado_id = 3
        orientador.save()
        sweetify.success(request,'Candidatura encerrada com sucesso', button='Ok', timer='3100', persistent="Close")
        return HttpResponseRedirect(reverse('docente:listar-Orientador-teseTcc'))

    sweetify.error(request,'solicitação invalida', button='Ok', timer='3100', persistent="Close")
    return HttpResponseRedirect(reverse('docente:listar-Orientador-teseTcc'))



def definirOrientador_teseTcc(request):
    form = OrientadorFrom(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            sweetify.success(request,'Orientador definido com sucesso', button='Ok', timer='3100', persistent="Close")
            form = OrientadorFrom()

    context = {'form': form}
    return render (request, 'docente/definirOrientador_teseTcc.html', context)



def atualizar_definirOrientador_teseTcc(request, pk):
    orientador = Orientador.objects.get(id=pk)
    form = OrientadorFrom(request.POST or None, instance=orientador)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            sweetify.success(request,'Dados atualizado com sucesso', button='Ok', timer='3100', persistent="Close")
            return HttpResponseRedirect(reverse('docente:listar-Orientador-teseTcc'))

    context = {'form': form, 'pk': pk}
    return render (request, 'docente/definirOrientador_teseTcc.html', context)



#@login_required
def consultar_dados_docente(request):
    form = ConsultarForm(request.POST or None)
    if request.method == "POST":
        nome = request.POST['nome'].upper()
        lista = Docente.objects.filter(Q(pessoa_nome__contains=nome) | Q(autor__contains=nome))
        context = {'lista': lista}
        return render (request, 'arquivos/listar_arquivos.html', context)

    context = {'form': form}
    return render (request, 'docente/listar_docente.html', context)



def atualizar_dados_docente(request, pk):
    pessoa = Pessoa.objects.get(id=pk)
    resp = Docente.objects.get(pessoa_id=pk)
    form = Pessoa_Form(request.POST or None, instance=pessoa)
    form2 = Docente_Form(request.POST or None, instance=resp)
    if request.method == "POST":
        form = Pessoa_Form(request.POST, request.FILES or None, instance=pessoa)
        if form.is_valid() and form2.is_valid():

            pessoa = form.save(commit=False)
            pessoa.municipio_id = form.cleaned_data.get('municipio')
            if len(request.POST['foto']) > 0:
                pessoa.foto = prepara_foto(request)
                pessoa.save()
            else:
                pessoa.foto ='user.jpg'
                pessoa.save()
            form2.save()

            sweetify.success(request, 'Dados atualizado com sucesso!....', button='Ok', timer='3100', persistent="Close")
            form = Pessoa_Form()
            form2 = Pessoa_Form()
            
    context = {'form': form, 'form2': form2, 'pk': pk}
    return render(request,  'docente/adicionar_docente.html', context)



def adicionar_docente(request):
    form = Pessoa_Form(request.POST or None)
    form2 = Docente_Form(request.POST or None)
    if request.method == "POST":
        form = Pessoa_Form(request.POST, request.FILES or None)
        if form.is_valid() and form2.is_valid():

            pessoa = form.save(commit=False)
            pessoa.municipio_id = form.cleaned_data.get('municipio')
            if len(request.POST['foto']) > 0:
                pessoa.foto = prepara_foto(request)
                pessoa.save()
            else:
                pessoa.foto ='user.jpg'
                pessoa.save()
            docente = form2.save(commit=False)
            docente.pessoa_id = pessoa.id
            docente.save()

            sweetify.success(request, 'Dados registado com sucesso!....', button='Ok', timer='3100', persistent="Close")
            form = Pessoa_Form()
            form2 = Pessoa_Form()
            
    context = {'form': form, 'form2': form2}
    return render(request,  'docente/adicionar_docente.html', context)

templates/docente/adicionar_docente.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 13:03:25
@modify date 2022-01-18 17:20:13
@desc [description]
-->
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      {% if pk is not None %}
      <div class="card-header"><h3>Atualizar dados do Docente</h3></div>
      <div class="card-body">
        <form id="regForm" class="forms-sample" action="{% url 'docente:atualizar-dados-docente' pk %}" method="POST" enctype="multipart/form-data">
          {% else %} 
          <div class="card-header"><h3>Cadastro do Docente</h3></div>
      <div class="card-body">
        <form id="regForm" class="forms-sample" action="{% url 'docente:adicionar-docente' %}" method="POST" enctype="multipart/form-data">
         {% endif %}
          {% csrf_token %} 
          {% autoescape on %}
          <div class="all-steps" id="all-steps"><span class="step"></span> <span class="step"></span> <span class="step"></span> <span class="step"></span></div>
          <div class="tab">
            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Nome Completo <span class="text-danger">*</span></label>
                  {{ form.nome }} <span class="text-danger">{{ form.nome.errors }}</span>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Nome do Pai</label>
                  {{ form.nome_pai }} {{ form.nome_pai.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Nome da Maẽ</label>
                  {{ form.nome_mae }} {{ form.nome_mae.errors }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Documento de Identificação <span class="text-danger">*</span></label>
                  {{ form.documento }} {{ form.documento.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Nº Identificação <span class="text-danger">*</span></label>
                  {{ form.ndi }} {{ form.ndi.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Data de Nascimento <span class="text-danger">*</span></label>
                  {{ form.data_nascimento }} {{ form.data_nascimento.errors }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Genero <span class="text-danger">*</span></label>
                  {{ form.genero }} {{ form.genero.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Estado Civil <span class="text-danger">*</span></label>
                  {{ form.estado_civil }} {{ form.estado_civil.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Nacionalidade</label>
                  {{ form.nacionalidade}} {{ form.nacionalidade.errors }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Provincia <span class="text-danger">*</span></label>
                  {{ form.provincia }} {{ form.provincia.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Munícipio <span class="text-danger">*</span></label>
                  {{ form.municipio }} {{ form.municipio.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Morada / Rua</label>
                  {{ form.residencia }} {{ form.residencia.errors }}
                </div>
              </div>
            </div>
          </div>
          <div class="tab">
            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Telefone <span class="text-danger">*</span></label>
                  {{ form.telefone }} {{ form.telefone.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">E-mail</label>
                  {{ form.email }} {{ form.email.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Número do Docente<span class="text-danger">*</span></label>
                  {{ form2.numero_docente }} {{ form2.numero_docente.errors }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="curso">Categoria do Docente<span class="text-danger">*</span></label>
                  {{ form2.categoria }} {{ form2.categoria.errors }}
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail3">Grau Academico <span class="text-danger">*</span></label>
                  {{ form2.grau_academico }} {{ form2.grau_academico.errors }}
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="">Situação<span class="text-danger">*</span></label>
                  {{ form2.estado }} {{ form2.estado.errors }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="">Data Registro<span class="text-danger">*</span></label>
                  {{ form2.data_registro }} {{ form2.data_registro.errors }}
                </div>
              </div>
            </div>
          </div>

          <div class="tab">
            <div class="row">
              <div class="col-md-4">
                <h4>Tira Fotografia</h4>
                <div class="card">
                  <div class="card-body text-center">
                    <div class="profile-pic mb-5">
                      <!--<img src="../img/user.jpg" width="150" class="rounded-circle" alt="user" />-->
                      <div id="my_camera"></div>
                    </div>
                  </div>
                  <div class="p-4 border-top mt-4">
                    <div class="row text-center">
                      <div class="col-6 border-right">
                        <a href="#" class="link d-flex align-items-center justify-content-center" onClick="configure()">
                          <i class="ik ik-message-square f-20 mr-5"></i>Ligar Camera
                        </a>
                      </div>
                      <div class="col-6">
                        <a href="#" class="link d-flex align-items-center justify-content-center" onClick="take_snapshot()"><i class="ik ik-box f-20 mr-5"></i>Foto</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-4">
                {{ form.foto }}
                <h4></h4>
                <div class="card">
                  <div class="card-body text-center">
                    <div class="profile-pic mb-20">
                      <div id="results"></div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-4">
                <h4></h4>
                <div class="card">
                  <div class="card-body text-center">
                    <div class="profile-pic mb-20">
                      <div id="result"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div style="overflow: auto" id="nextprevious">
            <div style="float: right">
              <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button> <button type="button" id="nextBtn" onclick="nextPrev(1)">Proximo</button>
            </div>
          </div>
          {% endautoescape %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/docente/atribuirDisciplina.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 10:16:57
@modify date 2021-09-26 11:15:01
@desc [description]
-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>

templates/docente/definirOrientador_teseTcc.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-02-01 13:56:12
@modify date 2022-02-02 01:52:46
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card" style="min-height: 484px">
      {% if pk is not null %}
      <div class="card-header"><h3>Definir Docente Como Orientador de TCC</h3></div>
      <div class="card-body">
        <form class="forms-sample" action="{% url 'docente:atualizar-definirOrientador-teseTcc' pk %}" method="POST">
        {% else %}
        <div class="card-header"><h3>Definir Docente Como Orientador de TCC</h3></div>
        <div class="card-body">
          <form class="forms-sample" action="{% url 'docente:definirOrientador-tese' %}" method="POST">
            {% endif %} {% csrf_token %} {% autoescape on %}
            <div class="form-group row">
              <label  class="col-sm-3 col-form-label">Docente</label>
              <div class="col-sm-9">{{ form.docente }}{{ form.docente.errors }}</div>
            </div>
            <div class="form-group row">
              <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Curso</label>
              <div class="col-sm-9">{{ form.curso }}{{ form.curso.errors }}</div>
            </div>

            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Número maximo de orientado</label>
              <div class="col-sm-9">{{ form.numero_orientados }}{{ form.numero_orientados.errors }}</div>
            </div>
             <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Desponibilidade</label>
              <div class="col-sm-9">{{ form.estado }}{{ form.estado.errors }}</div>
            </div>
            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Data limite de candidatura</label>
              <div class="col-sm-9">{{ form.data_limite }}{{ form.data_limite.errors }}</div>
            </div>
            
            <div class="form-group">
              <div id="visitfromworld" style="width: 100%; height: 50px"></div>
            </div>
            <button type="submit" class="btn btn-primary mr-2" style="width: 100%">Salvar</button>
            {% endautoescape %}
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/docente/listar_Orientador.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 12:33:14
@modify date 2022-02-02 14:03:56
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista de Docentes para Orientação de TCC</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Nome do Docente</th>
          <th>Curso</th>
          <th>Disponibilidade</th>
          <th>Número maximo de TCC</th>
          <th>Data Limite</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">
            <img src="/media/{{ dados.docente.pessoa.foto }}" alt="user" class="table-user-thumb" />
          </td>
          <td class="">Dr. {{ dados.docente.pessoa.nome|upper }}</td>
          <td class="">{{ dados.curso.nome }}</td>

          {% if dados.estdo.id == 3 %}
          <td class="alert bg-danger alert-danger text-white" role="alert">{{ dados.estado}}</td>
          {% else %}
          <td class="alert bg-success alert-success text-white" role="alert">{{ dados.estado }}</td>
          {% endif %}
          <td class="">{{ dados.numero_orientados }}</td>
          <td class="">{{ dados.data_limite }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'docente:atualizar-definirOrientador-teseTcc' dados.id %}">Atualizar</a>
                  {% if dados.estdo_id != 3 %}
                  <a class="dropdown-item" data-toggle="modal" data-target="#exampleModalLong">Solicitar o Orientador</a>
                  {% endif %}

                  <a class="dropdown-item" href="{% url 'docente:abriCandidatura-Orientador-teseTcc' dados.id %}">Abri a Candidatura</a>
                  <a class="dropdown-item" href="{% url 'docente:fecharCandidatura-Orientador-teseTcc' dados.id %}">Fechar a Candidatura</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongLabel">Solicitar o orientador para orientação do TCC</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
        <p>
          Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus
          auctor fringilla.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Enviar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/docente/listar_docente.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2021-09-26 12:33:14
@modify date 2022-01-20 23:32:02
@desc [description]
-->

{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista de Docentes Disponivel</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Nome</th>
          <th>Categoria</th>
          <th>Grau Academico</th>
          <th>Número do Docente</th>
          <th>Estado</th>
          <th>Data</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">
            <img src="/media/{{ dados.pessoa.foto }}" alt="user" class="table-user-thumb" />
          </td>
          <td class="">{{ dados.pessoa.nome|upper }}</td>
          <td class="">{{ dados.categoria.nome|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.grau_academico.nome|upper }}</td>
          <td class="">{{ dados.numero_docente }}</td>
          <td class="">{{ dados.estado }}</td>
          <td class="">{{ dados.data_registro|upper }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'docente:atualizar-dados-docente' dados.pessoa_id %}">ATUALIZAR</a>
                  <a class="dropdown-item" href="">DESATIVAR</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}